In [1]:
3+ 5* 4
#this is a math problem

23

In [3]:
weight_kg = 60

In [4]:
weight_kg = 60
# = is called the asssignment, like a sticky note with a value

In [5]:
print (weight_kg)

60


In [6]:
weight_kg*weight_kg
#to square something

3600

In [7]:
weight_kg * weight_kg

3600

In [8]:
# cannot have number as first character in variables

In [9]:
#case sensitive

In [10]:
my_number = 3
#integers

In [11]:
my_float = 2.43434434
my_string = 'this is my cool floating point number: '

In [12]:
print(my_string, my_float)

this is my cool floating point number:  2.43434434


In [13]:
weight_kg_text = 'weight in kilograms'
print (weight_kg_text, weight_kg)
print ('weight in pounds: ', weight_kg * 2.2)
print(weight_kg)
weight_kg = 100
print(weight_kg)

weight in kilograms 60
weight in pounds:  132.0
60
100


In [14]:
x = 5
y = 6
print(x+6)

11


In [15]:
x = y
print(x+y)

12


In [16]:
mass = 47.5
age = 122
mass = mass * 2.0
age = age -20
print(mass,age)

95.0 102


In [17]:
first, second = 'Grace', 'Shawn'
third, fourth = second, first
print(third, fourth)

Shawn Grace


In [18]:
#wasnt able to download file
#import numpy
#numpy.loadtxt (fname='inflammation-01.csv', delimiter=',')

In [19]:
import numpy

In [20]:
medical_data = numpy.loadtxt (fname='inflammation-01.csv',delimiter= ',')

In [22]:
import numpy as np

In [23]:
import numpy as np

In [24]:
#array
a = [1,2,3,4]


In [25]:
print (medical_data.shape)
#(row,columns)

(54, 40)


In [26]:
#data types
#int = 3, 6, 100
#floating point numbers: 3.434444, 1.2, 425.4243523452345224

In [30]:
print('first value in medical data: ',medical_data[0,0])

first value in medical data:  0.0


In [31]:
print('middle value in data', medical_data[30,20])

middle value in data 6.0


In [32]:
med_data_shape = medical_data.shape

middle_row = int(med-data_shape[0]/2)

In [33]:
middle_row = int(med_data_shape[0]/2)

In [34]:
print(med_data_shape)

(54, 40)


In [35]:
middle_col= int(med_data_shape[1]/2)

In [36]:
print(middle_row,middle_col)

27 20


In [37]:
print(medical_data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [38]:
#when [0:4], not including the fourth value
# zero is the first element

In [39]:
#each row is the patient, each column is the day

In [40]:
bruin=medical_data[:3, 36:]

In [41]:
print (bruin)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [42]:
# would be 0,1,2 and up to 40

In [43]:
#column is saying after/before this, so 36 is not included, and anything before 3, so 0,1,2

In [44]:
# : is called a slice

In [45]:
import time

In [46]:
print(time.ctime())

Mon Jan 27 10:24:47 2020


In [47]:
maxval, minval = np.max(medical_data), np.min(medical_data)

In [48]:
stdval=np.std(medical_data)

In [49]:
print('max:', maxval, ', min: ',minval, ',stdev:', stdval)

max: 19.0 , min:  0.0 ,stdev: 4.352194529455482


In [50]:
patient_1 = medical_data [0,:]

In [51]:
#all of the data for patient 0

In [52]:
print(patient_1)

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


In [54]:
print('max inflammation for patient 0:', np.max(patient_1))

max inflammation for patient 0: 18.0


In [55]:
patient_2 = medical_data [1,:]
patient_2_min= np.min(patient_2)

In [56]:
print(patient_2_min)

0.0


In [57]:
print(np.mean(medical_data, axis=1))

[5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1  ]


In [58]:
#each patient individual mean displayed

In [59]:
patients_mean=np.mean(medical_data, axis=1)

In [60]:
print(patients_mean)

[5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1  ]


In [62]:
patients_mean_down = np.mean(medical_data, axis =0)
print(patients_mean_down)

[ 0.          0.66666667  1.33333333  2.33333333  2.          1.66666667
  4.33333333  3.66666667  5.          6.          6.          7.
  6.33333333  6.33333333  5.          7.66666667  6.33333333 11.33333333
  9.66666667 11.33333333 14.33333333 10.33333333 11.66666667 11.
  8.66666667  8.66666667  8.66666667  6.          7.66666667  4.33333333
  5.66666667  4.66666667  4.33333333  4.33333333  3.33333333  4.
  1.66666667  2.          0.33333333  0.66666667]


In [63]:
print(patients_mean_down)

[ 0.          0.66666667  1.33333333  2.33333333  2.          1.66666667
  4.33333333  3.66666667  5.          6.          6.          7.
  6.33333333  6.33333333  5.          7.66666667  6.33333333 11.33333333
  9.66666667 11.33333333 14.33333333 10.33333333 11.66666667 11.
  8.66666667  8.66666667  8.66666667  6.          7.66666667  4.33333333
  5.66666667  4.66666667  4.33333333  4.33333333  3.33333333  4.
  1.66666667  2.          0.33333333  0.66666667]


In [64]:
def my_func(name): 
    print('Hello', name)

In [65]:
my_func('Shawn')

Hello Shawn


In [66]:
my_func("Shawn")

Hello Shawn


In [67]:
def square_minus(x): 
    square= x*x
    square = square -2
    return(square)

In [68]:
zzz = square_minus(4)

In [69]:
print(zzz)

14


In [112]:
square_minus

<function __main__.square_minus(x)>

In [113]:
square_minus(1)

-1

In [ ]:
#can set default numbers  when def
#x=4,y=3