In [1]:
element = oxygen

NameError: name 'oxygen' is not defined

In [2]:
element="oxygen"

In [4]:
print('first three characters:' ,element[0:3])

first three characters: oxy


In [5]:
print('last three characters:', element [3:6])

last three characters: gen


In [6]:
element [-1]

'n'

In [7]:
element[:4]

'oxyg'

In [8]:
element[4:]

'en'

In [9]:
element[:]

'oxygen'

In [10]:
element[-1]

'n'

In [11]:
element[-2]

'e'

In [12]:
element[1:-1]

'xyge'

In [13]:
#the code element[1:-1] records everything from the first character to the last

In [14]:
element[3:3]

''

In [15]:
#data[3;3,4:4] produces

In [16]:
#data[3:3, :1] produces an empty charcter with everything up to 1

In [18]:
import numpy as np

In [22]:
data = np.loadtxt("inflammation-01.csv", delimiter = ",")

In [23]:
print("en empty array:", data [3:3, 4:4])

en empty array: []


In [24]:
A= numpy.array([[1,2,3], [4,5,6], [7,8,9]])

In [25]:
print('A=')

A=


In [26]:
print (A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
B= numpy.hstack([A,A])

In [28]:
print(B)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [29]:
C= numpy.vstack([A,A])

In [30]:
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print("first and last of A:"," np.hstack([np.vstack(A[:,0]), np.vstack(A[:,2])]))

SyntaxError: EOL while scanning string literal (<ipython-input-33-4106e465ac71>, line 1)

In [34]:
print("first and last of A=", (A[1:-1]))

first and last of A= [[4 5 6]]


In [35]:
npdiff = numpy.array([0,2,5,9,14])

In [36]:
print(npdiff)

[ 0  2  5  9 14]


In [37]:
numpy.diff(npdiff)

array([2, 3, 4, 5])

In [39]:
#1: it would make sense to do the npdiff function across rows
#2: because diff subtracts the differnces of elements in a row, the resulting answer would subtract one column (60,39)

In [40]:
#3 How woud you find the largest change in inflammation for each patient?
#answer: calc npdiff and search for highest integer
#It does matter if the change in inflammation is increased or decreased. This would result in either a negative value or positie in npdiff

In [ ]:
#could you also use max/min= np.max (data, axis)